openapi: 3.0.0
info:
  title: Baggage API
  description: Maletapp Baggage api
  version: 0.0.1
paths:
  /baggages:
    get:
      tags:
        - Baggages
      summary: Get a list of the user baggages
      operationId: getBaggages
      responses:
        200:
          description: Baggage list retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Baggage'
        401:
          description: Unauthorized
        500:
          description: Internal server error
  /trips/{tripId}/baggages:
    get:
      tags:
        - Baggages
      summary: Get a list of the trip baggages
      operationId: getBaggagesByTrip
      parameters:
      - name: tripId
        in: path
        required: true
        description: ID of the trip
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Baggage list retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Baggage'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal server error
    post:
      tags:
        - Baggages
      summary: Create a new baggage
      operationId: createBaggage
      parameters:
      - name: tripId
        in: path
        required: true
        description: ID of the trip
        schema:
          type: string
          format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBaggage'
      responses:
        201:
          description: Baggage created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Baggage'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal server error
  /trips/{tripId}/baggages/{baggageId}:
    get:
      tags:
        - Baggages
      summary: Get a baggage by ID
      operationId: getBaggageById
      parameters:
      - name: tripId
        in: path
        required: true
        description: ID of the trip
        schema:
          type: string
          format: uuid
      - name: baggageId
        in: path
        required: true
        description: ID of the baggage to retrieve
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Baggage retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Baggage'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal server error

components:
  schemas:
    NewBaggage: 
      type: object
      properties:
        name:
          type: string
          description: The name for the baggage
    Baggage:
      allOf:
        - $ref: '#/components/schemas/NewBaggage'
        - type: object
          properties:        
            id:
              type: string
              format: uuid
              description: The unique identifier for the baggage
            tripId:
              type: string
              format: uuid
              description: The unique identifier for the trip that contains the baggage