openapi: 3.0.0
info:
  title: Items API
  description: Maletapp Items api
  version: 0.0.1
paths:
  /trips/{tripId}/baggages/{baggageId}/items:
    post:
      tags:
        - items
      summary: Create a new item on a baggage
      operationId: createItem
      parameters:
      - name: tripId
        in: path
        required: true
        description: ID of the trip
        schema:
          type: string
          format: uuid
      - name: baggageId
        in: path
        required: true
        description: ID of the baggage to retrieve
        schema:
          type: string
          format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewItem'
      responses:
        201:
          description: Item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        400:
          description: Bad request
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal server error
    get:
      tags:
        - items
      summary: Get a Item by ID
      operationId: getItemByBaggage
      parameters:
      - name: tripId
        in: path
        required: true
        description: ID of the trip
        schema:
          type: string
          format: uuid
      - name: baggageId
        in: path
        required: true
        description: ID of the baggage to retrieve
        schema:
          type: string
          format: uuid
      responses:
        200:
          description: Item retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Not Found
        500:
          description: Internal server error

components:
  schemas:
    NewItem:
      type: object
      allOf:
        - $ref: '#/components/schemas/ItemProperties'
        - required:
          - name
    PatchItem:
      type: object
      allOf:
        - $ref: '#/components/schemas/ItemProperties'
    Item:
      type: object
      allOf:
        - $ref: '#/components/schemas/ItemProperties'
        - required:
          - id
          - name
          - checkCount
    ItemProperties:
      type: object
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: The unique identifier for the item
        name:
          type: string
          description: The name of the item
        checkCount:
          type: integer
          description: Number of times this item has been checked
          minimum: 0
