openapi: 3.0.0
info:
  title: Trips API
  description: Maletapp Trips api
  version: 0.0.1
paths:
  /trips:
    get:
      tags:
        - Trips
      summary: Get a list of the user trips
      operationId: getTrips
      responses:
        200:
          description: Trip list retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Trip'
        401:
          description: Unauthorized
        500:
          description: Internal server error
    post:
      tags:
        - Trips
      summary: Create a new trip for the user
      operationId: createTrip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTrip'
      responses:
        201:
          description: Trip created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
  /trips/{tripId}:
    get:
      tags:
        - Trips
      summary: Get a trip by ID
      operationId: getTripById
      parameters:
        - name: tripId
          in: path
          required: true
          description: ID of the trip to retrieve
          schema:
            type: string
            format: uuid
      responses:
        200:
          description: Trip retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: Trip not found
        500:
          description: Internal server error
security:
  - bearerAuth: []

components:
  schemas:
    NewTrip: 
      allOf:
        - $ref: '#/components/schemas/TripProperties'
        - required:
          - destination
    Trip:
      allOf:
        - $ref: '#/components/schemas/TripProperties'
        - required:
          - id
          - destination
    TripProperties: 
      type: object
      properties:
        id:
          readOnly: true
          type: string
          format: uuid
          description: The unique identifier for the trip
        destination:
          type: string
          description: The destination of the trip
          nullable: true
        startDate:
          type: string
          format: date
          description: The start date of the trip
          nullable: true
        endDate:
          type: string
          format: date
          description: The end date of the trip
          nullable: true