openapi: 3.0.0
info:
  title: Trips API
  description: Maletapp Trips api
  version: 0.0.1
paths:
  /trips:
    post:
      tags:
        - Trips
      summary: Create a new trip
      operationId: createTrip
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTrip'
      responses:
        201:
          description: Trip created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal server error
security:
  - bearerAuth: []

components:
  schemas:
    NewTrip: 
      type: object
      properties:
        destination:
          type: string
          description: The destination of the trip
        startDate:
          type: string
          format: date
          description: The start date of the trip
        endDate:
          type: string
          format: date
          description: The end date of the trip
    Trip:
      allOf:
        - $ref: '#/components/schemas/NewTrip'
        - type: object
          properties:        
            id:
              type: string
              description: The unique identifier for the trip